server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    service.name: USER-SERVICE
    sender.type: web
  sleuth:
    enabled: true
    sampler:
    probability: 1.0
# Resttemplate configuration
rest.template:
  maxConnection: 400
  maxConnectionPerHost: 100
  socketTimeOut: 6000
  connectionTimeOut: 5000